version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'docker'
      POSTGRES_USER: 'adminn'
      POSTGRES_PASSWORD: 'adminnpass'
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./logs:/var/log
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G    
  backend:
    build: ./stocks_products
    command: gunicorn --bind 0.0.0.0:8000 stocks_products.wsgi:application
    expose:
    - 8000
    env_file:
      - ./.env  
    volumes:
      - static:/usr/src/stocks_products/staticfiles/  
    depends_on:
      - postgres
  nginx:
    build: ./nginx
    depends_on:
      - backend
    volumes:
      - static:/usr/src/stocks_products/staticfiles/  
    ports:
      - "8080:80"

volumes:
  static:      
